anomaly_clean: false
batch_size: 16
data_type: molecule
epochs: 100
freeze_layers: null
freeze_layers_reversed: false
kfold: 1
learning_rate: 0.0001
load_model_dir: null
logger_level: 1
max_epochs: 100
max_norm: 5.0
metrics:
- mse
- mae
- r2
model_name: unimolv2
model_size: 310m
num_classes: 1
patience: 10
remove_hs: false
seed: 42
smi_strict: true
smiles_col: smiles
split: random
split_group_col: scaffold
split_method: 1fold_random
split_seed: 42
target_col_prefix: ''
target_cols: D
target_normalize: auto
task: regression
use_amp: true
use_cuda: true
use_ddp: false
use_gpu: all
warmup_ratio: 0.03
